### PR TITLE
marshmallow3.x support

### PR DESCRIPTION
**Pull request by podhmo**
#29 

- using marshmallow 3.x is default
- if running with `--legacy` option, then the schema that 2.x like interface is used

### CODE REVIEW

**Comment by podhmo** [comment]
maybe working?

**Comment by Krolken** [comment]
I generated some code with my snake case resolver and it seemed to work fine on this branch.
I have to update some stuff manually but I think that is because of a crappy swagger file

**Comment by eLvErDe** [comment]
Hello,

I  used latest version + this PR to generate a quite complex model and it worked just fine. Are you waiting on something to merge ?

Regards

**Comment by podhmo** [comment]
Waiting marshmallow v3 release, when this PR is created.  The current status of marshmallow v3 is rc, isn't it? (so, stable version is 2.x, yet)

(:thought_balloon: Come to think of it, it is OK, to prepare that merging this PR)

**Comment by podhmo** [comment]
`--legacy` option is added

**Comment by podhmo** [comment]
https://github.com/marshmallow-code/marshmallow/issues/1154

**Comment by podhmo** [comment]
https://packaging.python.org/guides/distributing-packages-using-setuptools/?highlight=release#pre-release-versioning

**Comment by podhmo** [comment]
already released marshmallow 3.0.0, so merging this pr

**Pull request merged**
